import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Card } from "@/components/ui/card";
import { ResponsiveContainer, LineChart, Line, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, Legend } from "recharts";

export default function Analytics() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const [metrics, setMetrics] = useState<any[]>([]);

  useEffect(() => {
    if (!user) return;
    supabase.from("daily_metrics").select("*").order("metric_date").then(({ data }) => setMetrics(data || []));
  }, [user]);

  return (
    <div className="space-y-6 animate-fade-in">
      <div><h1 className="font-display text-3xl font-bold">{t("dash.analytics")}</h1><p className="text-muted-foreground mt-1">วิเคราะห์ผลลัพธ์จาก AI Bot</p></div>

      <div className="grid lg:grid-cols-2 gap-6">
        <ChartCard title="Revenue generated by AI">
          <LineChart data={metrics}>
            <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" opacity={0.3} />
            <XAxis dataKey="metric_date" stroke="hsl(var(--muted-foreground))" fontSize={11} tickFormatter={(v) => new Date(v).getDate().toString()} />
            <YAxis stroke="hsl(var(--muted-foreground))" fontSize={11} />
            <Tooltip contentStyle={{ background: "hsl(var(--popover))", border: "1px solid hsl(var(--border))", borderRadius: 8 }} />
            <Line type="monotone" dataKey="ai_revenue" stroke="hsl(250 95% 65%)" strokeWidth={2} dot={false} />
          </LineChart>
        </ChartCard>
        <ChartCard title="Conversion uplift">
          <LineChart data={metrics}>
            <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" opacity={0.3} />
            <XAxis dataKey="metric_date" stroke="hsl(var(--muted-foreground))" fontSize={11} tickFormatter={(v) => new Date(v).getDate().toString()} />
            <YAxis stroke="hsl(var(--muted-foreground))" fontSize={11} />
            <Tooltip contentStyle={{ background: "hsl(var(--popover))", border: "1px solid hsl(var(--border))", borderRadius: 8 }} />
            <Line type="monotone" dataKey="conversion_rate" stroke="hsl(190 95% 55%)" strokeWidth={2} dot={false} />
          </LineChart>
        </ChartCard>
        <ChartCard title="Chats per day">
          <BarChart data={metrics}>
            <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" opacity={0.3} />
            <XAxis dataKey="metric_date" stroke="hsl(var(--muted-foreground))" fontSize={11} tickFormatter={(v) => new Date(v).getDate().toString()} />
            <YAxis stroke="hsl(var(--muted-foreground))" fontSize={11} />
            <Tooltip contentStyle={{ background: "hsl(var(--popover))", border: "1px solid hsl(var(--border))", borderRadius: 8 }} />
            <Bar dataKey="chats_count" fill="hsl(220 90% 60%)" radius={[6, 6, 0, 0]} />
          </BarChart>
        </ChartCard>
        <ChartCard title="New vs Returning customers">
          <BarChart data={metrics}>
            <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" opacity={0.3} />
            <XAxis dataKey="metric_date" stroke="hsl(var(--muted-foreground))" fontSize={11} tickFormatter={(v) => new Date(v).getDate().toString()} />
            <YAxis stroke="hsl(var(--muted-foreground))" fontSize={11} />
            <Tooltip contentStyle={{ background: "hsl(var(--popover))", border: "1px solid hsl(var(--border))", borderRadius: 8 }} />
            <Legend />
            <Bar dataKey="new_customers" stackId="a" fill="hsl(250 95% 65%)" />
            <Bar dataKey="returning_customers" stackId="a" fill="hsl(190 95% 55%)" />
          </BarChart>
        </ChartCard>
      </div>
    </div>
  );
}

const ChartCard = ({ title, children }: { title: string; children: React.ReactElement }) => (
  <Card className="p-6 bg-gradient-card border-border/50">
    <h3 className="font-display font-semibold mb-4">{title}</h3>
    <ResponsiveContainer width="100%" height={240}>{children}</ResponsiveContainer>
  </Card>
);
